#!/usr/bin/env python3
"""Generate word-synced captions from a faster-whisper transcript.

Reads transcript.json (segment + word timestamps) and writes captions.js that,
when loaded by a composition, builds a bottom-center caption bar and registers
word-by-word reveal tweens on the composition's master timeline. Word times are
already in the tightened-timeline's global time, so they map 1:1 to the master.
"""

import json
from pathlib import Path

BASE = Path(__file__).resolve().parents[2] / "outputs" / "m1-longform-what-is-an-ai-agent"
TRANSCRIPT = BASE / "transcript.json"
OUT = BASE / "captions.js"


def build():
    data = json.loads(TRANSCRIPT.read_text())
    segs = data["segments"]

    # Per-segment word lists with global word index
    segments = []
    gi = 0
    for seg in segs:
        words = []
        for w in seg.get("words", []):
            words.append({"i": gi, "text": w["word"].strip(), "start": round(w["start"], 3)})
            gi += 1
        segments.append(
            {
                "start": round(seg["start"], 3),
                "end": round(seg["end"], 3),
                "words": words,
            }
        )

    payload = json.dumps(segments)

    js = f"""// Generated by gen_captions.py — word-synced captions.
// Loaded by the master composition. Adds caption reveals onto the passed timeline.
window.initCaptions = function (tl) {{
  var SEGMENTS = {payload};

  var cap = document.getElementById("caption");
  if (!cap || cap.dataset.built) return;
  cap.dataset.built = "1";
  cap.innerHTML = "";

  SEGMENTS.forEach(function (seg) {{
    var line = document.createElement("div");
    line.className = "cap-line";
    line.style.opacity = "0";
    seg.words.forEach(function (w) {{
      var span = document.createElement("span");
      span.className = "cap-word";
      span.id = "capw" + w.i;
      span.textContent = w.text + " ";
      span.style.opacity = "0.22";
      line.appendChild(span);
    }});
    cap.appendChild(line);
  }});

  // Show the active line at its segment start; hide at its end.
  SEGMENTS.forEach(function (seg, s) {{
    tl.to("#caption .cap-line:nth-of-type(" + (s + 1) + ")", {{ opacity: 1, duration: 0.15, ease: "power1.out" }}, seg.start);
    tl.to("#caption .cap-line:nth-of-type(" + (s + 1) + ")", {{ opacity: 0, duration: 0.15, ease: "power1.out" }}, Math.max(seg.end - 0.1, seg.start));
  }});

  // Reveal each word at its spoken timestamp.
  SEGMENTS.forEach(function (seg) {{
    seg.words.forEach(function (w) {{
      tl.to("#capw" + w.i, {{ opacity: 1, duration: 0.04, ease: "none" }}, w.start);
    }});
  }});
}};
"""
    OUT.write_text(js)
    print(f"Wrote {OUT} ({gi} words, {len(segments)} segments)")


if __name__ == "__main__":
    build()
